apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-g2sc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oyvw-tenant/rhtap-demo-app/hacbs-test-project-g2sc@sha256:be93c16c7f02a3247562802c180d5bb569099151897d8ac35cdbc01fe5d49ced
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
