apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-g2sc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-g2sc
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-g2sc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-g2sc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-g2sc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oyvw-tenant/rhtap-demo-app/hacbs-test-project-g2sc@sha256:c4b2fbd6a6b2ee133f88e079edad37170e555ff42fe8f576df6af8b59dfccbee
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
